<?php
require_once 'config.php';

header('Content-Type: application/json');

// Define your API credentials
define('SMS_API_KEY', 'fp58QdVYu0qzGy508yQMLA');
define('SMS_SENDER_ID', 'KARMAM');
define('WHATSAPP_API_URL', 'https://rcspro.in/v23.0/786573974548789/messages');
define('WHATSAPP_TOKEN', '4dfb629e-63c3-4706-8af6-007646a25e1a');

function sendSMS($phone, $otp) {
    try {
        $formatted_number = '91' . $phone;
        $message = "Your OTP for PF/EPS is $otp generated by Karma Management on behalf of Abbott.";
        
        $api_url = "https://cloud.smsindiahub.in/vendorsms/pushsms.aspx?" . 
                   "APIKey=" . SMS_API_KEY . 
                   "&msisdn=" . $formatted_number . 
                   "&sid=" . SMS_SENDER_ID . 
                   "&msg=" . urlencode($message) . 
                   "&fl=0&gwid=2";
        
        $response = @file_get_contents($api_url);
        
        if ($response === FALSE) {
            error_log("SMS API request failed for phone: $phone");
            return ['success' => false, 'error' => 'SMS API request failed'];
        }
        
        // Log response
        error_log("SMS API Response for $phone: " . $response);
        
        // Check for success indicators
        if (stripos($response, 'success') !== false || 
            stripos($response, 'sent') !== false || 
            stripos($response, '000') !== false ||
            stripos($response, '1701') !== false) {
            error_log("SMS sent successfully to $phone");
            return ['success' => true, 'message' => 'SMS sent successfully'];
        } else {
            error_log("SMS sending failed to $phone. Response: $response");
            return ['success' => false, 'error' => 'SMS sending failed'];
        }
        
    } catch (Exception $e) {
        error_log("SMS sending exception for $phone: " . $e->getMessage());
        return ['success' => false, 'error' => 'SMS exception: ' . $e->getMessage()];
    }
}

function sendWhatsappMessage($phone, $otp) {
    try {
        $apiUrl = WHATSAPP_API_URL;
        $token = WHATSAPP_TOKEN;
        
        $payload = [
            "messaging_product" => "whatsapp",
            "recipient_type" => "individual",
            "to" => "91" . $phone,
            "type" => "template",
            "template" => [
                "name" => "verify_code_1",
                "language" => ["code" => "en"],
                "components" => [
                    [
                        "type" => "body",
                        "parameters" => [
                            ["type" => "text", "text" => $otp]
                        ]
                    ]
                ]
            ]
        ];

        $ch = curl_init($apiUrl);
        curl_setopt($ch, CURLOPT_HTTPHEADER, [
            "Authorization: Bearer {$token}",
            "Content-Type: application/json"
        ]);
        curl_setopt($ch, CURLOPT_POST, true);
        curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($payload));
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_TIMEOUT, 10);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);

        $response = curl_exec($ch);
        $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        $curlError = curl_error($ch);
        curl_close($ch);

        // Log response for debugging
        error_log("WhatsApp API Response for $phone - HTTP: $httpCode, Response: $response");
        
        if ($curlError) {
            error_log("WhatsApp cURL Error: $curlError");
            return ['success' => false, 'error' => 'WhatsApp cURL error: ' . $curlError];
        }

        // Check for success (200 or 201)
        if ($httpCode == 200 || $httpCode == 201) {
            error_log("WhatsApp message sent successfully to $phone");
            return ['success' => true, 'message' => 'WhatsApp sent successfully'];
        } else {
            $responseData = json_decode($response, true);
            $errorMessage = $responseData['error']['message'] ?? 'Unknown error';
            error_log("WhatsApp sending failed to $phone. HTTP: $httpCode, Error: $errorMessage");
            return ['success' => false, 'error' => 'WhatsApp failed: ' . $errorMessage];
        }
        
    } catch (Exception $e) {
        error_log("WhatsApp sending exception for $phone: " . $e->getMessage());
        return ['success' => false, 'error' => 'WhatsApp exception: ' . $e->getMessage()];
    }
}

// Main execution
try {
    // Start session if not already started
    if (session_status() === PHP_SESSION_NONE) {
        session_start();
    }

    // Check if consent is given
    if (!isset($_SESSION['consent_given']) || $_SESSION['consent_given'] !== true) {
        throw new Exception("Consent required");
    }

    if (empty($_POST['phone'])) {
        throw new Exception("Phone number is required");
    }

    $phone = $_POST['phone'];
    
    // Validate phone number
    if (!preg_match('/^[0-9]{10}$/', $phone)) {
        throw new Exception("Invalid phone number format. Please enter 10-digit mobile number.");
    }

    // Get database connection
    $pdo = getDBConnection();
    
    // Check for existing valid OTP
    $checkStmt = $pdo->prepare("SELECT otp_code FROM otp_verification 
                               WHERE phone = ? AND verified = 0 
                               AND expires_at > NOW() AND attempts < ? 
                               ORDER BY created_at DESC LIMIT 1");
    $checkStmt->execute([$phone, MAX_OTP_ATTEMPTS]);
    $existingOtp = $checkStmt->fetch();

    if ($existingOtp) {
        // Use existing OTP
        $otp = $existingOtp['otp_code'];
        error_log("Using existing OTP for $phone: $otp");
    } else {
        // Generate new OTP
        $otp = generateOTP();

        // Store OTP in database
        if (!storeOTP($phone, $otp, 'sms')) {
            throw new Exception("Failed to generate OTP");
        }
        error_log("Generated new OTP for $phone: $otp");
    }

    // Store phone in session for verification
    $_SESSION['otp_phone'] = $phone;
    
    // Initialize tracking variables
    $smsResult = null;
    $whatsappResult = null;
    $errors = [];
    
    // Try to send SMS
    $smsResult = sendSMS($phone, $otp);
    if (!$smsResult['success']) {
        $errors[] = 'SMS: ' . $smsResult['error'];
        error_log("SMS failed for $phone: " . $smsResult['error']);
    }
    
    // Try to send WhatsApp
    $whatsappResult = sendWhatsappMessage($phone, $otp);
    if (!$whatsappResult['success']) {
        $errors[] = 'WhatsApp: ' . $whatsappResult['error'];
        error_log("WhatsApp failed for $phone: " . $whatsappResult['error']);
    }
    
    // Check if both failed
    if (!$smsResult['success'] && !$whatsappResult['success']) {
        $errorMessage = "Failed to send OTP via both methods:\n";
        $errorMessage .= implode("\n", $errors);
        throw new Exception($errorMessage);
    }
    
    // Determine success message based on what worked
    $smsSuccess = $smsResult['success'] ?? false;
    $whatsappSuccess = $whatsappResult['success'] ?? false;
    
    if ($smsSuccess && $whatsappSuccess) {
        $message = "OTP sent successfully via SMS and WhatsApp";
        $status = "both_sent";
    } elseif ($smsSuccess) {
        $message = "OTP sent successfully via SMS";
        $status = "sms_only";
    } else {
        $message = "OTP sent successfully via WhatsApp";
        $status = "whatsapp_only";
    }
    
    // Log final status
    error_log("Final sending status for $phone: " . $status);

    echo json_encode([
        'success' => true,
        'message' => $message,
        'phone' => $phone,
        'status' => $status,
        'sms_sent' => $smsSuccess,
        'whatsapp_sent' => $whatsappSuccess
    ]);

} catch (Exception $e) {
    error_log("OTP sending error: " . $e->getMessage());
    http_response_code(400);
    echo json_encode([
        'success' => false,
        'message' => $e->getMessage()
    ]);
}
?>